//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBASync.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VBASyncResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VBASyncResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VBASync.Localization.VBASyncResources", typeof(VBASyncResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+F4.
        /// </summary>
        public static string AltF4 {
            get {
                return ResourceManager.GetString("AltF4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Apply.
        /// </summary>
        public static string ApplyAction {
            get {
                return ResourceManager.GetString("ApplyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0} Chelsea Hughes. See {1} for more details..
        /// </summary>
        public static string AWCopyright {
            get {
                return ResourceManager.GetString("AWCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About VBA Sync Tool.
        /// </summary>
        public static string AWTitle {
            get {
                return ResourceManager.GetString("AWTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBA Sync Tool.
        /// </summary>
        public static string AWVBASyncTool {
            get {
                return ResourceManager.GetString("AWVBASyncTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AWVersion {
            get {
                return ResourceManager.GetString("AWVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit {0} for support..
        /// </summary>
        public static string AWWebsite {
            get {
                return ResourceManager.GetString("AWWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizes macros from an Office VBA-enabled file with a version-controlled folder..
        /// </summary>
        public static string AWWTFIsThis {
            get {
                return ResourceManager.GetString("AWWTFIsThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Browse.
        /// </summary>
        public static string BrowseAction {
            get {
                return ResourceManager.GetString("BrowseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelAction {
            get {
                return ResourceManager.GetString("CancelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} → {1} and file changed ({2}).
        /// </summary>
        public static string CDChangeFileType {
            get {
                return ResourceManager.GetString("CDChangeFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File changed ({0}).
        /// </summary>
        public static string CDWholeFile {
            get {
                return ResourceManager.GetString("CDWholeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file.
        /// </summary>
        public static string CTAddFile {
            get {
                return ResourceManager.GetString("CTAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string CTAddLines {
            get {
                return ResourceManager.GetString("CTAddLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sub.
        /// </summary>
        public static string CTAddSub {
            get {
                return ResourceManager.GetString("CTAddSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module type.
        /// </summary>
        public static string CTChangeFileType {
            get {
                return ResourceManager.GetString("CTChangeFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form design.
        /// </summary>
        public static string CTChangeFormControls {
            get {
                return ResourceManager.GetString("CTChangeFormControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string CTChangeLines {
            get {
                return ResourceManager.GetString("CTChangeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        public static string CTDeleteFile {
            get {
                return ResourceManager.GetString("CTDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete form design.
        /// </summary>
        public static string CTDeleteFrx {
            get {
                return ResourceManager.GetString("CTDeleteFrx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string CTDeleteLines {
            get {
                return ResourceManager.GetString("CTDeleteLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sub.
        /// </summary>
        public static string CTDeleteSub {
            get {
                return ResourceManager.GetString("CTDeleteSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string CTLicenses {
            get {
                return ResourceManager.GetString("CTLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename file.
        /// </summary>
        public static string CTMoveFile {
            get {
                return ResourceManager.GetString("CTMoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Sub.
        /// </summary>
        public static string CTMoveSub {
            get {
                return ResourceManager.GetString("CTMoveSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string CTProject {
            get {
                return ResourceManager.GetString("CTProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string CTReplaceId {
            get {
                return ResourceManager.GetString("CTReplaceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+L.
        /// </summary>
        public static string CtrlL {
            get {
                return ResourceManager.GetString("CtrlL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+O.
        /// </summary>
        public static string CtrlO {
            get {
                return ResourceManager.GetString("CtrlO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+S.
        /// </summary>
        public static string CtrlS {
            get {
                return ResourceManager.GetString("CtrlS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string CTWholeFile {
            get {
                return ResourceManager.GetString("CTWholeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find &apos;vbaProject.bin&apos; in ZIP archive..
        /// </summary>
        public static string ErrorCannotFindVbaProject {
            get {
                return ResourceManager.GetString("ErrorCannotFindVbaProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load WPF UI. If your system is non-Windows or otherwise doesn&apos;t support WPF, you may only run VBA Sync Tool by specifying -r on the command-line..
        /// </summary>
        public static string ErrorCannotLoadGUI {
            get {
                return ResourceManager.GetString("ErrorCannotLoadGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while decompressing stream &apos;{0}&apos;: {1}.
        /// </summary>
        public static string ErrorDecompressingStream {
            get {
                return ResourceManager.GetString("ErrorDecompressingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating OleColor: expected 4 bytes but saw {0} bytes as read..
        /// </summary>
        public static string ErrorFrxColorSizeMismatch {
            get {
                return ResourceManager.GetString("ErrorFrxColorSizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of OleSiteConcreteControl..
        /// </summary>
        public static string ErrorFrxExpectedEndOfOleSiteConcreteControl {
            get {
                return ResourceManager.GetString("ErrorFrxExpectedEndOfOleSiteConcreteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading &apos;{0}&apos; stream in .frx data: expected {1} size {2}, but saw {3} bytes as read..
        /// </summary>
        public static string ErrorFrxStreamSizeMismatch {
            get {
                return ResourceManager.GetString("ErrorFrxStreamSizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to file cannot be null or empty..
        /// </summary>
        public static string ErrorPathCannotbeNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorPathCannotbeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized module type..
        /// </summary>
        public static string ErrorUnrecognizedModuleType {
            get {
                return ResourceManager.GetString("ErrorUnrecognizedModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different stream lists in storage &apos;{0}&apos;.
        ///
        ///File 1: {{&apos;{1}&apos;}}
        ///
        ///File 2: {{&apos;{2}&apos;}}.
        /// </summary>
        public static string ExplainFrxDifferentFileLists {
            get {
                return ResourceManager.GetString("ExplainFrxDifferentFileLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different contents of stream &apos;{0}&apos; in storage &apos;{1}&apos;..
        /// </summary>
        public static string ExplainFrxGeneralStreamDifference {
            get {
                return ResourceManager.GetString("ExplainFrxGeneralStreamDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different contents of stream &apos;o&apos;, site &apos;{0}&apos; in storage &apos;{1}&apos;..
        /// </summary>
        public static string ExplainFrxOStreamDifference {
            get {
                return ResourceManager.GetString("ExplainFrxOStreamDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRX file difference.
        /// </summary>
        public static string ExplainFrxTitle {
            get {
                return ResourceManager.GetString("ExplainFrxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string MTClass {
            get {
                return ResourceManager.GetString("MTClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string MTForm {
            get {
                return ResourceManager.GetString("MTForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string MTIni {
            get {
                return ResourceManager.GetString("MTIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string MTLicenses {
            get {
                return ResourceManager.GetString("MTLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string MTStandard {
            get {
                return ResourceManager.GetString("MTStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string MTStaticClass {
            get {
                return ResourceManager.GetString("MTStaticClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About VBA Sync Tool.
        /// </summary>
        public static string MWAboutMenu {
            get {
                return ResourceManager.GetString("MWAboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string MWActionText {
            get {
                return ResourceManager.GetString("MWActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change type.
        /// </summary>
        public static string MWChangeType {
            get {
                return ResourceManager.GetString("MWChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MWDescription {
            get {
                return ResourceManager.GetString("MWDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MWEditMenu {
            get {
                return ResourceManager.GetString("MWEditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MWExitMenu {
            get {
                return ResourceManager.GetString("MWExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xtract VBA from Office file.
        /// </summary>
        public static string MWExtract {
            get {
                return ResourceManager.GetString("MWExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MWFileMenu {
            get {
                return ResourceManager.GetString("MWFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MWHelpMenu {
            get {
                return ResourceManager.GetString("MWHelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load last session.
        /// </summary>
        public static string MWLoadLastMenu {
            get {
                return ResourceManager.GetString("MWLoadLastMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open session.
        /// </summary>
        public static string MWLoadSessionMenu {
            get {
                return ResourceManager.GetString("MWLoadSessionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string MWModule {
            get {
                return ResourceManager.GetString("MWModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Office file.
        /// </summary>
        public static string MWOfficeFile {
            get {
                return ResourceManager.GetString("MWOfficeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string MWOpenAllFiles {
            get {
                return ResourceManager.GetString("MWOpenAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported files.
        /// </summary>
        public static string MWOpenAllSupported {
            get {
                return ResourceManager.GetString("MWOpenAllSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel 2007+ files.
        /// </summary>
        public static string MWOpenExcel07 {
            get {
                return ResourceManager.GetString("MWOpenExcel07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel 97-2003 files.
        /// </summary>
        public static string MWOpenExcel97 {
            get {
                return ResourceManager.GetString("MWOpenExcel97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook files.
        /// </summary>
        public static string MWOpenOutlook {
            get {
                return ResourceManager.GetString("MWOpenOutlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint 2007+ files.
        /// </summary>
        public static string MWOpenPpt07 {
            get {
                return ResourceManager.GetString("MWOpenPpt07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand-alone VBA project.
        /// </summary>
        public static string MWOpenSAlone {
            get {
                return ResourceManager.GetString("MWOpenSAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session files.
        /// </summary>
        public static string MWOpenSession {
            get {
                return ResourceManager.GetString("MWOpenSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word 2007+ files.
        /// </summary>
        public static string MWOpenWord07 {
            get {
                return ResourceManager.GetString("MWOpenWord07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word 97-2003 files.
        /// </summary>
        public static string MWOpenWord97 {
            get {
                return ResourceManager.GetString("MWOpenWord97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Publish VBA to Office file.
        /// </summary>
        public static string MWPublish {
            get {
                return ResourceManager.GetString("MWPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Refresh.
        /// </summary>
        public static string MWRefreshAction {
            get {
                return ResourceManager.GetString("MWRefreshAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save session.
        /// </summary>
        public static string MWSaveSessionMenu {
            get {
                return ResourceManager.GetString("MWSaveSessionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string MWSettingsMenu {
            get {
                return ResourceManager.GetString("MWSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBA Sync Tool.
        /// </summary>
        public static string MWTitle {
            get {
                return ResourceManager.GetString("MWTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _VBA project folder.
        /// </summary>
        public static string MWVBAFolder {
            get {
                return ResourceManager.GetString("MWVBAFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKAction {
            get {
                return ResourceManager.GetString("OKAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow adding new document modules when publishing (expert option).
        /// </summary>
        public static string SWAddNewDocumentsToFile {
            get {
                return ResourceManager.GetString("SWAddNewDocumentsToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After-extract hook.
        /// </summary>
        public static string SWAfterExtractHook {
            get {
                return ResourceManager.GetString("SWAfterExtractHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros: {TargetDir}.
        /// </summary>
        public static string SWAfterExtractHookHelp {
            get {
                return ResourceManager.GetString("SWAfterExtractHookHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before-publish hook.
        /// </summary>
        public static string SWBeforePublishHook {
            get {
                return ResourceManager.GetString("SWBeforePublishHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros: {TargetDir}.
        /// </summary>
        public static string SWBeforePublishHookHelp {
            get {
                return ResourceManager.GetString("SWBeforePublishHookHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow deleting document modules when publishing (expert option).
        /// </summary>
        public static string SWDeleteDocumentsFromFile {
            get {
                return ResourceManager.GetString("SWDeleteDocumentsFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Diff tool (optional).
        /// </summary>
        public static string SWDiffTool {
            get {
                return ResourceManager.GetString("SWDiffTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_iff tool parameters.
        /// </summary>
        public static string SWDiffToolParameters {
            get {
                return ResourceManager.GetString("SWDiffToolParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros: {OldFile}, {NewFile}.
        /// </summary>
        public static string SWDiffToolParametersHelp {
            get {
                return ResourceManager.GetString("SWDiffToolParametersHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SWGeneralTab {
            get {
                return ResourceManager.GetString("SWGeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore empty modules.
        /// </summary>
        public static string SWIgnoreEmpty {
            get {
                return ResourceManager.GetString("SWIgnoreEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language (requires restart).
        /// </summary>
        public static string SWLanguage {
            get {
                return ResourceManager.GetString("SWLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string SWOpenApplications {
            get {
                return ResourceManager.GetString("SWOpenApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search subdirectories of VBA project folder.
        /// </summary>
        public static string SWSearchRepositorySubdirectories {
            get {
                return ResourceManager.GetString("SWSearchRepositorySubdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string SWSessionTab {
            get {
                return ResourceManager.GetString("SWSessionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SWTitle {
            get {
                return ResourceManager.GetString("SWTitle", resourceCulture);
            }
        }
    }
}
